# The GitHub Actions docs (https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on)
# describe other options for 'on', 'pull_request' is a good default.
on: [pull_request]
jobs:
  digraph-integration-testing-cli:
    name: Digraph Call Integration Testing CLI
    runs-on: ubuntu-latest
    steps:
      - name: Setup Infracost
        uses: di-graph/config-validator-testing-github-actions/setup

      # Echo command
      - name: Echo Integration Testing CLI command
        run: |
          integration-testing-cli echo hello
